# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L67eLYK2X8rl8TMeFfI6-Wc8j4SIm_M_
"""

from tensorflow.keras import datasets

import pandas as pd
import numpy as np
import cv2
import time
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt

(data1, data2), (data3,data4) = datasets.cifar10.load_data()

len(data1)

t = time.time()
a=[]
for i in range(50000):
    image=data1[i]
    grayscale = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    if i%100 == 0:
        a.append(time.time() - t)
        t=time.time()
figure(figsize=(8, 6), dpi=80)
plt.plot(a)

